### ISSUE TITLE
pyproj link broken GOES-16: True Color notebook

### ISSUE THREAD

**Issue by julienchastang** [Unidata/python-gallery#105]
In `mapping_GOES16_TrueColor.ipynb` the pyproj link is broken. In addition, I wonder if we can eliminate references to pyproj since pyproj is no longer used in this notebook in lieu of cartopy. 

ping @blaylockbk

**Comment by blaylockbk** [comment]
I downloaded a copy of the repo and made some edits
- removed the links and reference to `pyproj`
- adjustments to comments formatting that might help in web display (removed markdown tables that don't seem to render)
- simplified a few lines of code

@julienchastang Could you walk me through the process to add these changes? This is my first time contributing to someone's else's repo. I need to make a pull request, right?

**Comment by julienchastang** [comment]
@blaylockbk actually the markdown tables do render (quite nicely, I think) in the notebooks. See the `python-gallery/notebooks` folder at https://jupyterhub.unidata.ucar.edu, for example.

**Comment by blaylockbk** [comment]
I see. I was looking at the webpage here:
https://unidata.github.io/python-gallery/examples/mapping_GOES16_TrueColor.html#sphx-glr-examples-mapping-goes16-truecolor-py.
It doesn't look like the tables where converted there.

*Brian*

**Comment by julienchastang** [comment]
Oh right. That I had not noticed. There are also a few other rendering problems. I think the technology here is at fault since the markdown is valid and renders correctly in other contexts. I'll try to dig into this. I also may break apart the issues/tasks i.e., verbiage changes vs rendering problems.
