### ISSUE TITLE
GOES-16: True Color Recipe Tables Not Rendering

### ISSUE THREAD

**Issue by julienchastang** [Unidata/python-gallery#112]
https://unidata.github.io/python-gallery/examples/mapping_GOES16_TrueColor.html#sphx-glr-examples-mapping-goes16-truecolor-py

@blaylockbk Do you see any other problems?

**Comment by blaylockbk** [comment]
Just the markdown tables and the hyperlinks didn't render on the website. Everything looks good in the notebook when I downloaded it.

**Comment by dopplershift** [comment]
This is fixed on the new training site.
