### ISSUE TITLE
Magic numbers in temperature advection example

### ISSUE THREAD

**Issue by sgdecker** [Unidata/python-gallery#28]
The 850-mb temperature example is great, but it is quite mysterious how you know the grid spacing is exactly 42583.44283066879 m in one direction and 55588.7366760194 m in the other. Shouldn't these values be calculated from the underlying data?

**Comment by dopplershift** [comment]
Yes, they should be. I'd merge a Pull Request correcting this... 😁

**Comment by dopplershift** [comment]
I think this is fixed in @kgoebber 's rewritten version: http://unidata.github.io/python-gallery/examples/850hPa_Temperature_Advection.html

Feel free to re-open if you disagree.
