### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by dopplershift** [Unidata/python-gallery#3]
Show how to make an animation in the notebook. Sources:
- Follow up on GINI
- GFS/HRRR
- MRMS

It might also be good to start with some simpler data first--like a simple timeseries plot.

One question is what format we can embed in the blog. We might be limited to html5 video, though that would mean we only need functionality present in matplotlib mainline.

**Comment by AodhanSweeney** [comment]
The new HurricaneTracker.py I uploaded   #124 should be an example of both the animation and the ipywidgets capabilities in notebooks. Only 3 years late!
