### ISSUE TITLE
Meteogram Example - Move to Canned Data

### ISSUE THREAD

**Issue by jrleeman** [Unidata/python-gallery#51]
Looks like the METAR data is giving us all NaN for pressure data and that's causing the y-limit setting to go sideways. Hazards of using "live" data I suppose. Maybe we should point the gallery at the Irma datasets? That would be interesting and consistent while still showing how to access data from THREDDS.

This looks to be a consequence of a regression in mpl https://github.com/matplotlib/matplotlib/issues/9361

**Comment by dopplershift** [comment]
Given the discussion that happened around the change for matplotlib (matplotlib/matplotlib#7460), I think we're on the hook for fixing this on our end.

**Comment by jrleeman** [comment]
I can see a couple of solutions, possibly both:

1. Make sure all the axes use `sharex=ax1`... I think that's a good idea anyway.
2. Use the temperature data for the range. All stations should have at least one point there.
3. Check for no temperature data? Shouldn't we just error there anyway?

**Comment by dopplershift** [comment]
Probably not. Matplotlib 2.0 improved default limits anyway (things like margins)

**Comment by tacaswell** [comment]
Might be worth adding a check to the Matplotlib code that ensures the auto-limits never blow up.  What sort of data are you feeding in that has this issue?

**Comment by dopplershift** [comment]
@tacaswell In this case we have live data that (apparently) was completely missing. This lead us to send `NaN`s to set xlim. Before matplotlib would give us a useless panel, now we get an error--the more I think about this, I'm not sad at the new behavior.

**Comment by jrleeman** [comment]
Let's move to canned data (case study or IEM) for now as we don't have a reliable surface feed from Unidata currently.
