### ISSUE TITLE
Problem running Miller example

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/python-gallery#60]
I tried to run the Miller Composite notebook (because I thought it might be a good one for @julienchastang poster) from
https://unidata.github.io/python-gallery/examples/miller_composite.html#sphx-glr-examples-miller-composite-py

and it's dying in cell [7] here:

https://gist.github.com/anonymous/3da3480e71a62a36983b68dc7ad398d6

what up?

**Comment by dopplershift** [comment]
You'd need to install numpy 1.11. Since then, they mucked with `gradient` to restrict the `dx` and `dy` to scalars. See Unidata/MetPy#174 .

**Comment by dopplershift** [comment]
You must not be running the `environment.yml` file for this repo, since that dependency is already encoded there...

**Comment by rsignell-usgs** [comment]
@dopplershift, True.  

I went to https://unidata.github.io/python-gallery/examples/miller_composite.html#sphx-glr-examples-miller-composite-py and clicked on "download Jupyter notebook", and since I wasn't missing any packages in the custom environment I was using, I didn't suspect that it would be a version issue in one of the packages.   

Would it be possible in sphinx gallery to add a link to the `environment.yml` close to where the `download as Jupyter notebook` link is?

**Comment by dopplershift** [comment]
No help from sphinx-gallery here, but a pull request adding install instructions and linking the environment from from the main gallery would be welcome!

**Comment by rsignell-usgs** [comment]
Not sure the best way to do this.   Closing since miller runs fine with specified environment .

**Comment by julienchastang** [comment]
@rsignell-usgs Open an issue at https://github.com/Unidata/xsede-jetstream/ if you think the problem lies there. (I did wonder, after we discussed this issue that the environment may simply be out of date.)

**Comment by julienchastang** [comment]
@dopplershift Would it be alright if I submitted a PR to add `nb_conda_kernels` to this project's `environment.yml`? Seems like a relevant addition to this notebook project. Moreover, I could then reuse this `environment.yml` file directly for https://github.com/Unidata/xsede-jetstream/issues/264.

**Comment by dopplershift** [comment]
@julienchastang in general, that's fine. The reason it's not is because this environment isn't intended for running a server that hosts different kernels. Is that what you need it to do? You only need to install `nb_conda_kernels` in the server's environment--the individual environments for each of the kernels don't actually need it installed.

**Comment by rsignell-usgs** [comment]
The individual kernels need ipykernel, right?

-Rich

**Comment by dopplershift** [comment]
Right--this is pulled in by `jupyter` listed in the `environment.yml` for this repository. Believe me, I've used this very environment with my own nb_conda_kernels setup. 😁

**Comment by julienchastang** [comment]
OK thanks for the clarification. No PR then.
