### ISSUE TITLE
Make This Project Easier to Use?

### ISSUE THREAD

**Issue by julienchastang** [Unidata/python-gallery#89]
Is there anyway to make this project easier to use? If I want to experiment with a notebook, say the Miller Composite Chart I currently clone

`git clone  https://github.com/Unidata/python-gallery`

At this point, I don't know where to look so I run `find . -name '*.ipynb' -print` and find nothing. 

I then I hop over to `gh-pages` branch hoping to find the notebooks. Sure enough this time `find` reveals:

```
./_downloads/2efb9f7572d606baf7a7ad2b7cf0391b/Ageostrophic_Wind_Example.ipynb
...
./_downloads/af0a8029589d8efd9084299025c8265a/miller_composite.ipynb
```

If I want to build the conda environment to run these notebooks, I hop back over to `master` because that is where `environment.yml` is located.

Is there anyway to have a top-level `notebooks` directory and a co-located `environment.yml` from the branch that gets checked out by default?

**Comment by jrleeman** [comment]
I think you've got to think of this from how the community interacts with it - not how developers interact. All of the examples are available for download as notebooks or scripts here: http://unidata.github.io/python-gallery/examples/index.html

Due to the way sphinx gallery works we can't keep notebooks in the main repository as they are really build artifacts, not original contributions.

**Comment by julienchastang** [comment]
The zip file (I did not know about the zip file) will work best for my scenario which is a zero to jupyterhub `lifecycleHooks`.  I can grab and unpack the zip file there. And by this point the conda environment has already been built by the container and made available with `nb_conda_kernels` so no problem there either. We can close this issue.

**Comment by julienchastang** [comment]
Though the zip download has a non-predictable URL: http://unidata.github.io/python-gallery/_downloads/63bf60e63cf05e60479ca15024a50062/examples_jupyter.zip so I'll have to find another solution.

**Comment by dopplershift** [comment]
@julienchastang The link isn't discoverable, but the hash is "just" the hash of the filename, so the link *should* be stable--though it appears not stable between build platforms, but stable on the same one. Ugly, but stable.

**Comment by julienchastang** [comment]
Alrighy, I will give that a shot. I agree, it makes the most sense to simply use OSS projects out-of-the-box with as little ad-hoc customizations on our end to reduce maintenance and cognitive load.
