### ISSUE TITLE
Using Xarray for Data read and selection example appears broken

### ISSUE THREAD

**Issue by spencermathews** [Unidata/python-gallery#97]
In the [Using Xarray for Data read and selection](https://unidata.github.io/python-gallery/examples/xarray_500hPa_map.html) example the call to `xr.open_dataset()` fails with the following error:

    ValueError: dimensions ('time',) must have the same length as the number of data dimensions, ndim=2

**Comment by jrleeman** [comment]
Hi @spencermathews - can you provide some more details? I've tested locally and do not see this error.

- Are you running the gallery conda environment we have available in the repo?
- What OS are you on?
- If you are not running the gallery environment, please include the output of a `conda list` command.

**Comment by spencermathews** [comment]
I resolved the problem by installing the `netcdf4` library. Without it xarray makes a failed attempt to open the URL using the `pydap` backend. It would be helpful to mention `netcdf4` as an implied dependency on the example page and in the downloadable script and notebook.

By comparison, the [500 hPa Geopotential Heights and Winds](https://unidata.github.io/python-gallery/examples/500hPa_HGHT_Winds.html) does work with `pydap`, event in the absence of `netcdf4`.

I wasn't using the gallery environment&mdash; it might be useful to mention it somewhere on the **python-gallery** website, not just on the README, so that visitors to the site are made aware of it.

**Comment by jrleeman** [comment]
Glad you got it resolved and that's a great suggestion! Thanks!
